server:
  address: 127.0.0.1
  port: 12346
  max-http-header-size: 10000000
  # 优雅停机,接收命令后将不再接收新的请求,默认是immediate.kill -9不会触发优雅停机,需使用kill -2
  shutdown: graceful
  servlet:
    # 指定url后缀,若不指定访问接口时直接就是ip:port/api,该参数加上则是ip:port/study/api
    context-path: /websocket
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    
spring:
  profiles:
    #第一个参数是开发环境配置文件,其他的多个配置文件必须以application-开头,只用写后缀即可,逗号隔开
    active: dev,socketio
  application:
    name: dream-study-java-websocket
  # 优雅停机时设置最大等待时间,超过该时间立刻停机
  lifecycle:
    timeout-per-shutdown-phase: 30s