jasypt:
  encryptor:
    password: 必须配置或在启动时输入.加解密密钥,安全起见,不要写在配置文件中,在启动时写入该命令
    algorithm: 必须配置或在启动时输入.加解密算法,需要和加密时使用算法相同,JDK8一般为PBEWithMD5AndDES,默认为PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: 必须配置或在启动时输入.需要和加密时使用IV生成器相同,如果加密时未使用,配置为org.jasypt.iv.NoIvGenerator
    property:
      prefix: 筛选需要解密的属性前缀,默认为ENC(
      suffix: 筛选需要解密的属性后缀,默认为)

spring:
  datasource:
    # 使用jasypt加密后的用户名,ENC(密文)为固定写法.例如明文为yang_wan,密钥为9ZvUNNxDsZmjNLrn,使用PBEWithMD5AndDES算法,无IV,加密后为e9KIvF4dxNJ0BWxoVSiLhZcV8DwopQ1k
    username: ENC(e9KIvF4dxNJ0BWxoVSiLhZcV8DwopQ1k)