
package com.wy.wsdl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsdlServiceImpl", targetNamespace = "http://server.wsdl.wy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsdlServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsername", targetNamespace = "http://server.wsdl.wy.com/", className = "com.wy.wsdl.client.GetUsername")
    @ResponseWrapper(localName = "getUsernameResponse", targetNamespace = "http://server.wsdl.wy.com/", className = "com.wy.wsdl.client.GetUsernameResponse")
    @Action(input = "http://server.wsdl.wy.com/WsdlServiceImpl/getUsernameRequest", output = "http://server.wsdl.wy.com/WsdlServiceImpl/getUsernameResponse")
    public String getUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.wy.wsdl.client.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://server.wsdl.wy.com/", className = "com.wy.wsdl.client.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://server.wsdl.wy.com/", className = "com.wy.wsdl.client.GetUserResponse")
    @Action(input = "http://server.wsdl.wy.com/WsdlServiceImpl/getUserRequest", output = "http://server.wsdl.wy.com/WsdlServiceImpl/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
