dream:
  socketio:
   host: localhost
   port: 8503
   max-frame-payload-length: 1048576
   max-http-content-length: 1048576
   boss-count: 1
   work-count: 100
   allow-custom-requests: true
   upgrade-timeout: 10000
   ping-timeout: 60000
   ping-interval: 25000