spring:
  profiles:
    active:
    - config
    - mail
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    async:
      request-timeout: 180S
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
  transaction: 
    rollback-on-commit-failure: true
  redis:
    host: 172.30.252.13
  cache:
    type: redis