spring:
  application:
    name: dream-study-java-kaptcha
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    async:
      request-timeout: 180S
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
  transaction: 
    rollback-on-commit-failure: true
  redis:
    host: 172.30.252.13
    password: admin$%123
    database: 15
  cache:
    type: redis
    
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc://localhost:3306/test
    
server:
  port: 8080