spring:
  ai:
    vectorstore:
      redis:
        initialize-schema: true  # 启动时自动创建索引
        index-name: my-knowledge-base # 索引名称
    openai:
      # 全局配置
      base-url: https://api.siliconflow.cn
      api-key: ${SILICONFLOW_API_KEY}
      chat:
        # 指定某一个API配置(覆盖全局配置)
        #api-key: sk-xxx
        #base-url: https://api.openai.com/
        options:
          # 模型配置
          model: Qwen/Qwen2.5-7B-Instruct
      # 向量模型

  data:
    redis:
      host: 