spring:
  ai:
    openai:
      # 全局配置
      base-url: https://api.openai.com/
      api-key: sk-xxx
      chat:
        # 指定某一个API配置(覆盖全局配置)
        api-key: sk-xxx
        base-url: https://api.openai.com/
        options:
          # 模型配置
          model: gpt-3.5-turbo

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${ALIYUN_AI_KEY}
      model-name: qwen-plus