shiro:
  resource:
    systemcode: shiro-mgt
  framework:
    jwt:
      base64-encoded-secret-key: qazwsx1234567890
    shiro:
      redis:
        nodes: redis://192.168.1.112:6379,redis://192.168.1.112:6380,redis://192.168.1.112:6381,redis://192.168.1.112:7379,redis://192.168.1.112:7380,redis://192.168.1.112:7381
        connect-timeout: 6000
        connect-pool-size: 150
        connection-minimumidle-size: 30
        timeout: 6000
        global-session-timeout: 3600000
  datasource:
    shiro:
      work-id: 10
      primary-key: id
      data-source-name: shiro-data-source
      xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/shiro
      password: root
      username: root
      initial-size: 20
      max-active: 200
      max-life-time: 3600000
      min-idle: 10
      max-wait: 6000
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      remove-abandoned: false
      remove-abandoned-timeout: 60000
      log-abandoned: true
      filters: mergeStat
      type-aliases-package: com.wy.shiro.entity
      mapper-locations: classpath*:mapper/*.xml

spring:
  jta:
    atomikos:
      properties:
        log-base-dir: E:/logs/spring-shiro
        transaction-manager-unique-name: dream-study-java-shiro