spring:
  devtools:
    restart:
      enabled: false
      exclude: static/**,public/**,*.md
  profiles:
    active:
    - config
    - mail
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    async:
      request-timeout: 180S
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
  transaction: 
    rollback-on-commit-failure: true
  security:
    user:
      name: admin
      password: 123456
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8&tinyInt1isBit=false&allowMultiQueries=true
    username: root
    password: 123456
      
management:
  endpoints:
    web:
      exposure:
        include:
        # *表示暴露info,health所有端点
        - "*"
  endpoint:
    health:
      # 默认是NEVER
      show-details: always
      
info:
  test: test
  version: 0.0.1