spring:
  profiles:
    active:
    - config
    - mail
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    async:
      request-timeout: 180S
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
  transaction: 
    rollback-on-commit-failure: true
  security:     user:      name: admin
      password: 123456
management:  endpoints:    web:      exposure:        include:
       # *表示暴露info,health所有端点        - "*"
  endpoint:    health:
      # 默认是NEVER      show-details: ALWAYS
info:
  test: test
  version: 0.0.1

server: 
  port: 5510
  max-http-header-size: 10000000
  # 数据压缩
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - image/png
    - image/jpeg
    - image/jpg
    - text/html
    - text/css
    - application/javascript
    - application/octet-stream
    - application/json
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true