server:
    tomcat:
      # 当所有可能的请求处理线程都在使用时,传入连接请求的最大队列长度,默认100
      accept-count: 100
      # 服务器在任何给定时间接受和处理的最大连接数,一旦达到限制,操作系统仍然可以接受基于acceptCount属性的连接,默认8192
      max-connections: 8192
      # 在关闭连接之前可以通过管道传输的HTTP请求的最大数量.当为0或1时,将禁用keep-alive和管道处理;当为-1时,允许无限数量的保持活动的请求
      max-keep-alive-requests: 100
      max-http-form-post-size: 2MB
      max-swallow-size: 2MB
      # 连接器在接受连接后等待显示请求 URI 行的时间
      connection-timeout: 20000
      # 在关闭连接之前等待另一个 HTTP 请求的时间。如果未设置，则使用 connectionTimeout。设置为 -1 时不会超时
      keep-alive-timeout: 20000
      threads:
        # 工作线程的最大数量.io密集型建议10倍的cpu数,cpu密集型建议cpu数+1,绝大部分应用都是io密集型
        max: 200
        # 工作线程的最小数量,初始化时创建的线程数
        min-spare: 10
      
      