spring:
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.sina.com
    port: 25
    username: mygodness30@sina.com
    password: 
    properties: 
      mail:
        transprot:
          # 邮件发送协议
          protocol: stmp
        # 邮件服务器地址
        host: smtp.qq.com
        smtp:
          # 是否验证用户名,密码
          auth: true
          # 是否使用ssl安全连接
          ssl:
            enable: true
