server:
  address: 8888
  max-http-header-size: 10000000
  servlet:
    encoding:
      # 指定http请求和相应的Charset,默认UTF-8
      charset: UTF-8
      # 是否开启http的编码支持,默认为true
      enabled: false
      # 是否强制对http请求和响应进行编码,默认为true
      force: true
      force-request: true
      force-response: true
  # 数据压缩
  compression:
    enabled: true
    # 启用压缩的最小响应大小,单位为字节
    min-response-size: 1024
    # 压缩文件类型,默认为"text/html", "text/xml", "text/plain", "text/css", "text/javascript","application/javascript", "application/json", "application/xml" 
    mime-types:
    - image/png
    - image/jpeg
    - image/jpg
    - text/css
    - text/html
    - text/plain
    - text/xml
    - text/javascript
    - application/javascript
    - application/json
    - application/octet-stream
    - application/xml