# 日志配置
logging:
  # 指定日志地址,默认是加载classpath下的spring-logback.xml,logback.xml,logback-test.xml
  config: classpath:spring-logback.xml
  # 日志输出格式
  pattern: 
    # 输出到控制台
    console: "%(%d{yyyy-MM-dd HH:mm:ss})  [%p]  %(%C:%L)  : %m %n"
    # 输出到文件
    file: "%(%d{yyyy-MM-dd HH:mm:ss})  [%p]  %(%C:%L)  : %m %n"
  level:
    # 全局日志输出级别
    root: INFO
    # 配置包的日志输出级别
    '[org.springframework.web.servlet]': WARN
    # 打印mybatis的sql日志,前面为mapper接口所在的包
    '[com.wy.mapper]': debug
    # 分组标识,表示该分组所有包日志级别都是DEBUG
    level-debug: DEBUG
    level-warn: WARN
    
  file: 
    # 日志文件名称
    name: logger.log
    # 日志文件输出路径
    path: D:\\Java
    # 单个日志文件最大大小
    max-size: 15MB
    # 日志保存最大天数
    max-history: 30
  group:
    # 指定分组标识,唯一
    level-debug:
    - org.springframework.web.servlet
    - com.wy.mapper
    level-warn:
    - com.wy.common