xxl: 
  job:
    # admin管理后台地址
    admin-addresses: http://127.0.0.1:8080/xxl-job-admin
    access-token: 
    executor: 
      appname: xxl-job-executor-sample
      address: 
      ip:
      port: 9999
      log-path: ../applogs/xxl-job/jobhandler
      log-retention-days: 30